server {
    listen 3015;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Redirect all requests to index.html to allow Angular routing
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets for better performance
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}